name = "atelier-olda"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[build]
command = "npm install && npm run build"

[env.production]
name = "atelier-olda"

# Enable logging for debugging
[observability]
enabled = true
